version: '3.1'
services:
  db:
    build: ./postgres/
    restart: always
    networks:
      - bridge1
    volumes:
      - database:/var/lib/postgresql/data
      - backup:/backup
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: "898asa43sdfas9d244ses"
      POSTGRES_DB: "postgres"


volumes:
  database:
  backup:

networks:
  bridge1:
    driver: bridge