FROM postgres:12.2-alpine
WORKDIR /docker-entrypoint-initdb.d
ADD . .
RUN mkdir /backup
RUN chown -R postgres:postgres /backup
RUN chmod -R 700 /backup
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d
RUN chmod -R 700 /docker-entrypoint-initdb.d